### ISSUE TITLE
Transportation Groups

### ISSUE THREAD

**Issue by cheeseburgur101** [promdate/Promdate#16]
This is something we should discuss more about before starting. Is there a user limit on groups? Will they be able to chat from within groups? Either way, don't start on this yet until we get a better understanding of what we want.

**Comment by loganarmack** [comment]
From my understanding it's not really a social media platform—people should be communicating elsewhere. I thought it would just be that one person books transportation, then is able to invite whoever else they want.

**Comment by emccart** [comment]
- [ ] Add groups
   - [ ] Add group invites
       - [ ] Accept invites
       - [ ] Decline invites
   - [ ] Add group ownership and management
       - [ ] Create groups
       - [ ] Delete groups
   - [ ] Other group functionality
       - [ ] Join groups (pretty much just accept invites)
       - [ ] Leave groups
