### ISSUE TITLE
Record user statistics

### ISSUE THREAD

**Issue by cheeseburgur101** [promdate/Promdate#28]
The database table exists, however now I'd like to include the type of device a user made the request from. Edit the `log_event()` function in `/php/funcs.php` to save the user's device in the `Extra` column.

**Comment by loganarmack** [comment]
Wouldn't this take up a lot of memory though?

**Comment by cheeseburgur101** [comment]
not really. There's 3 INT columns, and 3 VARCHAR columns. The ints are 11 bytes each, both the Type and IPAddress column will be less than 40 bytes, and the last varchar column isn't required. Added up, each entry in this table could take up ~100 bytes. You could store a whopping 10 million entries in a single Gigabyte of disk space.

**Comment by cheeseburgur101** [comment]
All of the important API calls log events (in the betterAdminPanel branch). If someone wants more events on top of what's already there feel free to reopen the issue

**Comment by Max-Y-Huang** [comment]
The device needs to be logged
