### ISSUE TITLE
Fix Database Issue (Non-urgent)

### ISSUE THREAD

**Issue by cheeseburgur101** [promdate/Promdate#31]
Curretntly, the database uses 2 columns for determining if a user is matched or not. `Matched` which is either `1` or `0` describes if they are fully matched. (i.e they send a request, someone accepted). `PartnerID` contains the UserID of the partner they have matched with. Both columns are returned when getting a user's status and are always public to other users. However, when a user has only sent out a match request, the UserID of the request is stored in the `PartnerID` column. An unintentional side effect is now everyone can see who has requested to be with who before the other person accepts.

**Comment by loganarmack** [comment]
You could make the server return -1 if the matched variable is false instead of returning both

**Comment by emccart** [comment]
https://github.com/promdate/Promdate/compare/nonurgent I think I got it
