### ISSUE TITLE
Token lifetimes

### ISSUE THREAD

**Issue by cheeseburgur101** [promdate/Promdate#46]
For added security tokens should only last at most a week. Clients should get a new token every so often using the `regentoken.php` file to make sure that the user never has to log in a second time.

**Comment by loganarmack** [comment]
"Every so often" could just be every time they open up the app again, right?

**Comment by emccart** [comment]
yeah that sounds good

**Comment by emccart** [comment]
This is done when the app implements it.

**Comment by loganarmack** [comment]
This is a server side thing, not an app side thing. You want the tokens to actually stop working, not just for the app to generate new ones.

**Comment by emccart** [comment]
Tokens regen from the app. Now they just need to expire after time. Might be worthwhile to create a function that runs on every API call that clears tokens with a certain time difference or greater.
