### ISSUE TITLE
Make all API calls use json_encode for returning JSON instead of doing it manualy

### ISSUE THREAD

**Issue by cheeseburgur101** [promdate/Promdate#60]
PHP provides a module for encoding and decoding JSON with `json_encode()` and `json_decode()`. What I'd like to do is use these for the return values of API calls instead of just using sketchy hand-crafted JSON.

**Comment by cheeseburgur101** [comment]
Issue solved in the betterAdminPanel branch, waiting on PR

**Comment by Max-Y-Huang** [comment]
Do `assoc_array_to_json()` and `json_encode()` do the same thing ? (ie. can all instances of `assoc_array_to_json() be replaced with json_encode()`?)

**Comment by Max-Y-Huang** [comment]
Anyone working on this?
